name: CI

on:
  repository_dispatch:
    branches:
    - workflows-test
  push:
    branches:
    - workflows-test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world! changed.
    - name: Docker step
      uses: ./.github/actions/docker